name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  despliegue:
    runs-on: hostinger
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Install Packages
        run: composer install

      - name: Apply migrations
        run: php artisan migrate

      - name: Copy Public HTML
        run: copy -r . /home/u777467137/public_html
